### PR TITLE
Avoid reversing text order in @property comment

### PR DESCRIPTION
**Pull request by deiwin**
As mentioned in #227, this will remove the limited markdown restriction from *property* documentation.

### CODE REVIEW

**Comment by deiwin** [comment]
The contribution guidelines suggest updating the `CHANGELOG` which I think would be warranted here, but I don't actually see such file in the repository.

**Comment by deiwin** [comment]
As I'm building a separate theme anyway, I'm not that concerned about the second commit getting merged. So, @inossidabile, if you'd like, I could split this into 2 separate PRs as well.

**Comment by inossidabile** [comment]
Yes, please split. And it makes #227 useless, right?

**Comment by deiwin** [comment]
I'll do that next week.

**Comment by deiwin** [comment]
Removed the other commit (the one that removed the limited markdown limitation from `@property`), as I understand you're not interested in merging that.

#227 is still a bug that makes this project sometimes behave in an unexpected way. I would strongly suggest not ignoring that PR.

**Pull request merged**
